HTML = "text/html"
HTM = "text/html"
TXT = "text/plain"
CSS = "text/css"
CSV = "text/csv"
XML = "application/xml"
JSON = "application/json"
JS = "application/javascript"

PNG = "image/png"
JPG = "image/jpeg"
JPEG = "image/jpeg"
GIF = "image/gif"
BMP = "image/bmp"
WEBP = "image/webp"
SVG = "image/svg+xml"
ICO = "image/x-icon"
TIF = "image/tiff"
TIFF = "image/tiff"
AVIF = "image/avif"

MP3 = "audio/mpeg"
WAV = "audio/wav"
OGG = "audio/ogg"
M4A = "audio/mp4"
AAC = "audio/aac"
FLAC = "audio/flac"

MP4 = "video/mp4"
WEBM = "video/webm"
AVI = "video/x-msvideo"
MOV = "video/quicktime"
MKV = "video/x-matroska"

WOFF = "font/woff"
WOFF2 = "font/woff2"
TTF = "font/ttf"
OTF = "font/otf"
EOT = "application/vnd.ms-fontobject"

PDF = "application/pdf"
ZIP = "application/zip"
TAR = "application/x-tar"
GZ = "application/gzip"
RAR = "application/vnd.rar"
SEVEN_Z = "application/x-7z-compressed"
EXE = "application/octet-stream"
BIN = "application/octet-stream"
APK = "application/vnd.android.package-archive"
MSI = "application/x-msdownload"
DEB = "application/vnd.debian.binary-package"

DOC = "application/msword"
DOCX = "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
XLS = "application/vnd.ms-excel"
XLSX = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
PPT = "application/vnd.ms-powerpoint"
PPTX = "application/vnd.openxmlformats-officedocument.presentationml.presentation"
